config/routes.rb
Webapp::Application.routes.draw do

  resources :blogposts

  resources :funds

  post "likes/vote"
  resources :likes

  get "notifications/check_notification"
  resources :notifications

  post "circles/add_circle"
  post "circles/add_person"
  post "circles/remove_person"
  get "circles/send_access_request"
  get "circles/confirm_request"
  resources :circles

  post "tags/add_tag"
  post "tags/delete_tag"
  resources :tags

  resources :locations

  get "votes/vote_description"
  post "votes/vote_description"
  get "votes/show_votes"
  resources :votes

  get "ideas/show_idea"
  get "ideas/show_replies"
  resources :ideas

  resources :documents

  get "campaigns/guide_step"
  post "campaigns/next_step"
  get "campaigns/basic_step"
  post "campaigns/create_step"
  get "campaigns/about_step"
  post "campaigns/description_step"
  get "campaigns/circles_step"
  get "campaigns/publish_step"
  post "campaigns/upload_logo"
  post "campaigns/update_description"
  post "campaigns/update_name"

  get "authentications/login"
  post "authentications/remote_login"
  post "authentications/create"
  get "authentications/wrong_link"
  get "authentications/forgot_password"
  post "authentications/forgot_password"
  get "authentications/new"
  get "authentications/logout"
  get "authentications/checklogin"
  post "authentications/process_login"
  post "authentications/update_password"
  resources :authentications

  post "pictures/upload_picture"
  post "pictures/edit_picture"
  post "pictures/delete_picture"
  resources :pictures

  post "companydescriptions/new_suggestion"
  post "companydescriptions/update_description"
  resources :companydescriptions

  resources :companyupdates

  get "investors/unfollowcompany"
  get "investors/follow_company"
  get "investors/add_mentor"
  get "investors/delete_mentor"
  get "investors/people"
  get "investors/newstartup"
  get "investors/history_startup"
  post "investors/search_people"
  post "investors/add_founder"
  post "investors/remove_founder"
  get "investors/confirm_founder"
  get "investors/follower_info"
  get "investors/last_activities"
  post "investors/share_with_fund"
  post "investors/unshare_with_fund"
  resources :investors

  get "users/update"
  get "users/index"
  get "users/edit"
  get "users/change_password"
  get "users/notifications"

  post "colleagues/join_fund"
  post "colleagues/unjoin_fund"

  resources :users 

  get "startups/index"
  get "startups/team"
  get "startups/show"
  post "startups/search_startups"
  get "startups/circles"
  get "startups/dashboard"
  get "startups/hashtag"
  get "startups/my_ideas"
  get "startups/following_ideas"
  get "startups/show_more_startups"
  get "startups/request_access"
  post "startups/upload_link"
  get "startups/track_progress"

  resources :startups
  
  resources :peoples
  

  get "home/about"
  get "home/signup"
  get "home" => 'home#index'
  resources :home

  get "tri_valley_meetup" => 'tri_valley_meetup#signup'
  get "tri_valley_meetup/show"
  get "tri_valley_meetup/update_profile"
  get "tri_valley_meetup/profile"
  get "tri_valley_meetup/signup"
  get "tri_valley_meetup/add_to_fund"
  get "tri_valley_meetup/logout"
  post "tri_valley_meetup/wrong_login"
  post "tri_valley_meetup/delete_info"
  post "tri_valley_meetup/login"
  post "tri_valley_meetup/create_account"
  get "tri_valley_meetup/change_password"
  get "tri_valley_meetup/forgot_password"
  post "tri_valley_meetup/forgot_password"
  get "tri_valley_meetup/admin_view"
  post "tri_valley_meetup/send_email"

  post "userinfos/add_experience"
  post "userinfos/add_ask"
  post "userinfos/delete_info"
  post "userinfos/delete_experience"
  post "userinfos/delete_ask"

  root :to => 'home#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :event_id, :event_type, :status, :user_id

  belongs_to :user

  # event_type
  # 1 - add to the team
  # 2 - remove from the team
  # 3 - add access to idea
  # 4 - remove access to idea

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json


  def check_notification
    user = User.find(session[:id])

    if user
      notifications = Notification.where("user_id = ? AND status = 1", user.id)
      if notifications
        total_notifications = notifications.length
        notification = Notification.find(params[:id])
        if notification
          notification.update_attribute(:status, 0)
          user.update_attribute(:notification_num, total_notifications-1)
        end
        respond_to do |format|
          format.js
        end
      end
    end

  end


  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br />
    <%= f.number_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/check_notification.js.erb
var elNode = document.getElementById("notification<%= params[:id]%>");
var newP = document.createElement("span")
newP.innerHTML = "checked";
elNode.parentNode.replaceChild(newP, elNode);

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Status</th>
    <th>Event type</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.user_id %></td>
    <td><%= notification.status %></td>
    <td><%= notification.event_type %></td>
    <td><%= notification.event_id %></td>
    <td><%= link_to 'Show', notification %></td>
    <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
    <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @notification.user_id %>
</p>

<p>
  <b>Status:</b>
  <%= @notification.status %>
</p>

<p>
  <b>Event type:</b>
  <%= @notification.event_type %>
</p>

<p>
  <b>Event:</b>
  <%= @notification.event_id %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>